import Head from "next/head";

import { NumStoreUI } from "../components/NumberStore";
import { StrStoreUI } from "../components/StringStore";
import { ConnectWallet } from "../components/ConnectWallet";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Challenge 02 - Force Transaction Confirmation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ConnectWallet />
        <br /> <hr />
        <NumStoreUI />
        <br /> <br /> <hr />
        <StrStoreUI />
      </main>
    </div>
  );
}
