import Head from 'next/head';

import { NumStoreUI } from '../components/NumberStore';
import { StrStoreUI } from '../components/StringStore';
import { ConnectWallet } from '../components/ConnectWallet';
import { ErrorModalProvider } from '../contexts/ErrorModalContext';
import Toast from '../components/Toast';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Challenge 02 - Force Transaction Confirmation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ErrorModalProvider>
          <ConnectWallet />
          <br /> <hr />
          <NumStoreUI />
          <br /> <br /> <hr />
          <StrStoreUI />
        </ErrorModalProvider>
        <Toast />
      </main>
    </div>
  );
}
